#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 1.0.{build}
os: WMF 5
install:
  - ps: Write-Host 'Install'

environment:
  MySecureVar:
    secure: 2miEAGV72ED32TvZbXUbQA== #This is secured
  MyNonSecureVar: NonSecure
  ModuleName: appVeyorDemo
#---------------------------------# 
#      build configuration        # 
#---------------------------------# 
build_script: 
  - ps: Write-Host 'Build'

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 
test_script: 
  - ps: Write-Host 'Test'

#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 
deploy_script: 
  - ps: Write-Host 'Deploy'