#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 1.0.{build}
os: WMF 5
install:
  - ps: Import-Module .\AppVeyor\Functions\AppVeyor-Util.psm1 | Out-Null
  - ps: . .\AppVeyor\install.ps1

environment:
  NuGetApiKey:
    secure: UIr9SZkDLqMe2EjAP2CBmvomalY6sRAenwlLYR3fRDdyUhB1/RO7nsvYFRGM36RD
  GHToken:
    secure: 5jmXah8zuXr+gjrG1WkD1uZ/jk9q7W+foC793X8//rJN5vdye5tice7j83mPuuwU
  ModuleName: PSDummy

#---------------------------------# 
#      build configuration        # 
#---------------------------------# 
build: off

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 
test_script: 
  - ps: . .\AppVeyor\test.ps1

#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 
deploy_script: 
  - ps: . .\AppVeyor\deploy.ps1

#Skip build when pushing a new tags
skip_tags: true

#GitHub Pull Request notifications
notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: 5jmXah8zuXr+gjrG1WkD1uZ/jk9q7W+foC793X8//rJN5vdye5tice7j83mPuuwU
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"


